import { defineMessages } from 'react-intl';

const messages = defineMessages({
  more: {
    id: 'Link more',
    defaultMessage: 'Link more',
  },
  LinkTitle: {
    id: 'Link title',
    defaultMessage: 'Link Title',
  },
  LinkTo: {
    id: 'Link to',
    defaultMessage: 'Link to',
  },
  altText: {
    id: 'Alt text',
    defaultMessage: 'Alt text',
  },
  altTextAiGenerated: {
    id: 'Was this alt text generated by an AI?',
    defaultMessage: 'Was this alt text generated by an AI?',
  },
});

const schemaHero = ({ intl }) => {
  return {
    title: 'Block settings',
    required: [],
    fieldsets: [
      {
        id: 'default',
        title: intl.formatMessage(messages.more),
        fields: [
          'linkTitle',
          'linkHref',
          // INTERAKTIV START
          'alt',
          'alt_ai_generated',
          // END
        ],
      },
    ],
    properties: {
      linkTitle: {
        title: intl.formatMessage(messages.LinkTitle),
      },
      linkHref: {
        title: intl.formatMessage(messages.LinkTo),
        widget: 'object_browser',
        mode: 'link',
        selectedItemAttrs: ['Title', 'Description'],
        allowExternals: true,
      },
      // INTERAKTIV START
      alt: {
        title: intl.formatMessage(messages.altText),
      },
      alt_ai_generated: {
        type: 'boolean',
        title: intl.formatMessage(messages.altTextAiGenerated),
      },
      // END
    },
  };
};
export default schemaHero;
