import { defineMessages } from 'react-intl';

const messages = defineMessages({
  altTextGenStartLabel: {
    id: 'An alternative text is being generated in the background.',
    defaultMessage: 'An alternative text is being generated in the background.'
  },
  altTextGenSuccessTitle: {
    id: 'Success',
    defaultMessage: 'Success'
  },
  altTextGenSuccessLabel: {
    id: 'The alternative text was generated successfully.',
    defaultMessage: 'The alternative text was generated successfully.'
  },
  aiGeneratedAltLabel: {
    id: 'Was this alt text generated by an AI?',
    defaultMessage: 'Was this alt text generated by an AI?',
  }
});

export default messages;
