import { defineMessages } from 'react-intl';

const messages = defineMessages({
  altTextGenStartLabel: {
    id: 'An alternative text is being generated in the background.',
    defaultMessage: 'An alternative text is being generated in the background.'
  },
  altTextGenSuccessTitle: {
    id: 'Success',
    defaultMessage: 'Success'
  },
  altTextGenSuccessLabel: {
    id: 'The alternative text was generated successfully.',
    defaultMessage: 'The alternative text was generated successfully.'
  },
  aiGeneratedAltLabel: {
    id: 'Was this alt text generated by an AI?',
    defaultMessage: 'Was this alt text generated by an AI?',
  },
  altTextGenErrorTitle: {
    id: 'Error',
    defaultMessage: 'Error'
  },
  altTextGenNotAllowed: {
    id: 'The generation of alt texts is disabled for this content.',
    defaultMessage: 'The generation of alt texts is disabled for this content.'
  },
  altTextGenErrorLabel: {
    id: 'The alt text generation failed.',
    defaultMessage: 'The alt text generation failed.'
  },
});

export default messages;
